<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CreatePositionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('positions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('callsign', 30);
            $table->string('name', 30);
            $table->string('fir', 4);
            $table->unsignedInteger('rating');
        });

        // Denmark
        DB::table('positions')->insert([
            ['callsign' => 'AFRC_FSS', 'name' => 'Africa Central Control', 'fir' => 'AFRC', 'rating' => 5],
            ['callsign' => 'AFRS_FSS', 'name' => 'Africa South Control', 'fir' => 'AFRS', 'rating' => 5],
            ['callsign' => 'AFRW_A_FSS', 'name' => 'Africa West Control', 'fir' => 'AFRW', 'rating' => 5],
            ['callsign' => 'DBBB_APP', 'name' => 'Cotonou Approach', 'fir' => 'DGAC', 'rating' => 4],
            ['callsign' => 'DBBB_TWR', 'name' => 'Cotonou Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DGAA_APP', 'name' => 'Accra Approach', 'fir' => 'DGAC', 'rating' => 4],
            ['callsign' => 'DGAA_GND', 'name' => 'Accra Ground', 'fir' => 'DGAC', 'rating' => 2],
            ['callsign' => 'DGAA_TWR', 'name' => 'Accra Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DGAC_CTR', 'name' => 'Accra Control', 'fir' => 'DGAC', 'rating' => 5],
            ['callsign' => 'DGAC_N_CTR', 'name' => 'Accra Control', 'fir' => 'DGAC', 'rating' => 5],
            ['callsign' => 'AFRW_B_FSS', 'name' => 'Africa West Control', 'fir' => 'AFRW', 'rating' => 5],
            ['callsign' => 'DGLE_APP', 'name' => 'Tamale Approach', 'fir' => 'DGAC', 'rating' => 4],
            ['callsign' => 'DGSI_TWR', 'name' => 'Kumasi Approach/Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DGSN_TWR', 'name' => 'Sunyani Approach/Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DGTK_TWR', 'name' => 'Takoradi Approach/Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DIAP_APP', 'name' => 'Abidjan Approach', 'fir' => 'GOOO', 'rating' => 4],
            ['callsign' => 'DIAP_TWR', 'name' => 'Abidjan Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'DIBK_TWR', 'name' => 'Bouake Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'DIII_CTR', 'name' => 'Abidjan Control', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'DISP_TWR', 'name' => 'San Pedro Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'DIYO_TWR', 'name' => 'Yamoussoukro Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'DNAA_APP', 'name' => 'Abuja Approach', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNAA_GND', 'name' => 'Abuja Ground', 'fir' => 'DNKK', 'rating' => 2],
            ['callsign' => 'DNAA_TWR', 'name' => 'Abuja Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNAI_TWR', 'name' => 'Uyo Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNAK_TWR', 'name' => 'Akure Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNBE_TWR', 'name' => 'Benin Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNBK_TWR', 'name' => 'Kebbi Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNCA_APP', 'name' => 'Calabar Tower/Approch', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNDS_TWR', 'name' => 'Dutse Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNEN_TWR', 'name' => 'Enugu Tower/Approach', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNES_TWR', 'name' => 'Escravos Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNFB_TWR', 'name' => 'Finimi Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNGO_TWR', 'name' => 'Gombe Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNIB_TWR', 'name' => 'Ibadan Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNIL_APP', 'name' => 'Ilorin Approach/Tower', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNIM_TWR', 'name' => 'Owerri Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNJO_TWR', 'name' => 'Jos Approach/Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNKA_APP', 'name' => 'Kaduna Tower', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNKK_CTR', 'name' => 'Kano Control', 'fir' => 'DNKK', 'rating' => 5],
            ['callsign' => 'DNKK_W_CTR', 'name' => 'Kano Control', 'fir' => 'DNKK', 'rating' => 5],
            ['callsign' => 'DNKN_APP', 'name' => 'Kano Approach', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNKN_TWR', 'name' => 'Kano Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNKT_TWR', 'name' => 'Katsina Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNMA_APP', 'name' => 'Maiduguri Tower', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNMM_APP', 'name' => 'Lagos Approach', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNMM_CTR', 'name' => 'Lagos West', 'fir' => 'DNKK', 'rating' => 5],
            ['callsign' => 'DNMM_GND', 'name' => 'Lagos Ground', 'fir' => 'DNKK', 'rating' => 2],
            ['callsign' => 'DNMM_TWR', 'name' => 'Lagos Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNMN_TWR', 'name' => 'Minna Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNPO_APP', 'name' => 'Port Harcourt Approach', 'fir' => 'DNKK', 'rating' => 4],
            ['callsign' => 'DNPO_TWR', 'name' => 'Port Harcourt Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNSO_TWR', 'name' => 'Sokoto Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNSU_TWR', 'name' => 'Osubi Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNYO_TWR', 'name' => 'Yola Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DNZA_TWR', 'name' => 'Zaria Tower', 'fir' => 'DNKK', 'rating' => 3],
            ['callsign' => 'DXNG_TWR', 'name' => 'Niamtougou Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'DXXX_CTR', 'name' => 'Lome Control', 'fir' => 'DGAC', 'rating' => 5],
            ['callsign' => 'DXXX_TWR', 'name' => 'Lome Tower', 'fir' => 'DGAC', 'rating' => 3],
            ['callsign' => 'FABE_TWR', 'name' => 'Bhisho Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FABL_APP', 'name' => 'Blomfontein Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FABL_TWR', 'name' => 'Blomfontein Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FABW_I_TWR', 'name' => 'Karoo Radio', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FACA_CTR', 'name' => 'Cape Town Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FACA_E_CTR', 'name' => 'Cape Town Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FACT_APP', 'name' => 'Cape Town Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FACT_DEL', 'name' => 'Cape Town Delivery', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FACT_F_APP', 'name' => 'Cape Town Director', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FACT_GND', 'name' => 'Cape Town Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FACT_TWR', 'name' => 'Cape Town Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAEL_APP', 'name' => 'East London Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAEL_TWR', 'name' => 'East London Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAGC_TWR', 'name' => 'Grand Central Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAGG_APP', 'name' => 'George Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAGG_TWR', 'name' => 'George Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAGM_TWR', 'name' => 'Rand Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAHS_APP', 'name' => 'Hoedspruit Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAHS_GND', 'name' => 'Hoedspruit Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAMR_I_CTR', 'name' => 'Lowveld Information', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAHS_TWR', 'name' => 'Hoedspruit Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAJA_C_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_E_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_NW_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_SE_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_SW_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FAJA_W_CTR', 'name' => 'Johannesburg Area', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'AFRW_FSS', 'name' => 'Africa West Control', 'fir' => 'AFRW', 'rating' => 5],
            ['callsign' => 'DGAO_CTR', 'name' => 'Accra Radio', 'fir' => 'DGAC', 'rating' => 5],
            ['callsign' => 'FAJO_1_FSS', 'name' => 'Johannesburg Oceanic', 'fir' => 'FAJO', 'rating' => 5],
            ['callsign' => 'FAJO_2_FSS', 'name' => 'Johannesburg Oceanic', 'fir' => 'FAJO', 'rating' => 5],
            ['callsign' => 'FAKM_A_GND', 'name' => 'Kimberley Apron Office', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAKM_APP', 'name' => 'Kimberley Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAKM_TWR', 'name' => 'Kimberley Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAKN_APP', 'name' => 'Kruger Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAKN_I_APP', 'name' => 'Kruger Radio', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FALA_GND', 'name' => 'Lanseria Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FALA_TWR', 'name' => 'Lanseria Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FALE_APP', 'name' => 'Durban Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FALE_GND', 'name' => 'King Shaka Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FALE_I_APP', 'name' => 'Durban Radio', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FALE_TWR', 'name' => 'King Shaka Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FALM_APP', 'name' => 'Makhado Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FALM_GND', 'name' => 'Makhado Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FALM_TWR', 'name' => 'Makhado Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FALW_APP', 'name' => 'Langebaanweg Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FALW_GND', 'name' => 'Langebaanweg Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FALW_TWR', 'name' => 'Langebaanweg Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAMM_TWR', 'name' => 'Mafikeng Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAOB_APP', 'name' => 'Overberg Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAOH_I_TWR', 'name' => 'Oudtshoorn Radio', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAOR_A_GND', 'name' => 'O.R. Tambo Apron Office', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAOR_APP', 'name' => 'Johannesburg Radar', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAOR_DEL', 'name' => 'O.R. Tambo Clearance Delivery', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAOR_E_TWR', 'name' => 'O.R. Tambo Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAOR_F_APP', 'name' => 'O.R. Tambo Director', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAOR_GND', 'name' => 'O.R. Tambo Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAOR_TWR', 'name' => 'O.R. Tambo Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAOR_V_APP', 'name' => 'Johannesburg Radio', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAOR_W_APP', 'name' => 'Johannesburg Radar', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAPA_I_TWR', 'name' => 'Port Alfred Radio', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAPE_APP', 'name' => 'Port Elizabeth Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FAPE_DEL', 'name' => 'Port Elizabeth Clearance Delivery', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAPE_TWR', 'name' => 'Port Elizabeth Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAPM_TWR', 'name' => 'Pietermaritzburg Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAPN_TWR', 'name' => 'Pilanesburg Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAPP_TWR', 'name' => 'Polokwane Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FARB_TWR', 'name' => 'Richards Bay Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FASA_CTR', 'name' => 'South Africa Control', 'fir' => 'FASA', 'rating' => 5],
            ['callsign' => 'FASK_TWR', 'name' => 'Swartkops Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FASZ_I_TWR', 'name' => 'Skukuza Radio', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAUP_TWR', 'name' => 'Upington Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAUT_TWR', 'name' => 'Mthatha Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAVG_TWR', 'name' => 'Virginia Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAWB_GND', 'name' => 'Wonderboom Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAWB_TWR', 'name' => 'Wonderboom Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAWK_GND', 'name' => 'Waterkloof Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAWK_TWR', 'name' => 'Waterkloof Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FAYP_GND', 'name' => 'Ysterplaat Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FAYP_TWR', 'name' => 'Ysterplaat Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FBGR_CTR', 'name' => 'Gaborone Control', 'fir' => 'FBGR', 'rating' => 5],
            ['callsign' => 'FBKE_APP', 'name' => 'Kasane Approach', 'fir' => 'FBGR', 'rating' => 4],
            ['callsign' => 'FBKE_TWR', 'name' => 'Kasane Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FBLV_TWR', 'name' => 'Limpopo Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FBMN_APP', 'name' => 'Maun Approach', 'fir' => 'FBGR', 'rating' => 4],
            ['callsign' => 'FBMN_GND', 'name' => 'Maun Ground', 'fir' => 'FBGR', 'rating' => 2],
            ['callsign' => 'FBMN_TWR', 'name' => 'Maun Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FBPM_APP', 'name' => 'PG Matante Approach', 'fir' => 'FBGR', 'rating' => 4],
            ['callsign' => 'FBPM_TWR', 'name' => 'PG Matante Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FBSK_APP', 'name' => 'Gaborone Approach', 'fir' => 'FBGR', 'rating' => 4],
            ['callsign' => 'FBSK_GND', 'name' => 'Gaborone Ground', 'fir' => 'FBGR', 'rating' => 2],
            ['callsign' => 'FBSK_TWR', 'name' => 'Gaborone Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FBSP_TWR', 'name' => 'Selebi Tower', 'fir' => 'FBGR', 'rating' => 3],
            ['callsign' => 'FCBB_APP', 'name' => 'Brazzaville Approach', 'fir' => 'FCCC', 'rating' => 4],
            ['callsign' => 'FCBB_TWR', 'name' => 'Brazzaville Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FCCC_CTR', 'name' => 'Brazzaville Control', 'fir' => 'FCCC', 'rating' => 5],
            ['callsign' => 'FCPD_TWR', 'name' => 'Dolisie Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FCPP_APP', 'name' => 'Pointe Noire Approach', 'fir' => 'FCCC', 'rating' => 4],
            ['callsign' => 'FCPP_TWR', 'name' => 'Pointe Noir Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FDMS_GND', 'name' => 'Matsapha Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FDMS_TWR', 'name' => 'Matsaph Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FDSK_APP', 'name' => 'Matsapha Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FDSK_GND', 'name' => 'Sikhuphe Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FEFF_TWR', 'name' => 'Bangui Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FGSL_TWR', 'name' => 'Malabo Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FHSH_APP', 'name' => 'St Helena Approach', 'fir' => 'FNAN', 'rating' => 4],
            ['callsign' => 'FHSH_TWR', 'name' => 'St Helena Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FIMM_CTR', 'name' => 'Mauritius Centre', 'fir' => 'FIMM', 'rating' => 5],
            ['callsign' => 'FIMM_FSS', 'name' => 'Mauritius Radio', 'fir' => 'FIMM', 'rating' => 5],
            ['callsign' => 'FIMP_APP', 'name' => 'Mauritius Approach', 'fir' => 'FIMM', 'rating' => 4],
            ['callsign' => 'FIMP_TWR', 'name' => 'Mauritius Tower', 'fir' => 'FIMM', 'rating' => 3],
            ['callsign' => 'FIMR_TWR', 'name' => 'Corail Tower', 'fir' => 'FIMM', 'rating' => 3],
            ['callsign' => 'FJDG_GND', 'name' => 'Diego Garcia Ground', 'fir' => 'FIMM', 'rating' => 2],
            ['callsign' => 'FJDG_TWR', 'name' => 'Diego Garcia Tower', 'fir' => 'FIMM', 'rating' => 3],
            ['callsign' => 'FKKD_TWR', 'name' => 'Douala Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FKKK_CTR', 'name' => 'Doual Control', 'fir' => 'FCCC', 'rating' => 5],
            ['callsign' => 'FKKN_TWR', 'name' => 'Ngaoundere Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FKYS_APP', 'name' => 'Nsimalen Approach', 'fir' => 'FCCC', 'rating' => 4],
            ['callsign' => 'FKYS_TWR', 'name' => 'Nsimalen Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FLCP_I_TWR', 'name' => 'Chipata Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLFI_CTR', 'name' => 'Lusaka Control', 'fir' => 'FLFI', 'rating' => 5],
            ['callsign' => 'FLHN_APP', 'name' => 'Livingstone Approach', 'fir' => 'FLFI', 'rating' => 4],
            ['callsign' => 'FLHN_TWR', 'name' => 'Livingstone Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLKK_APP', 'name' => 'Lusaka Approach', 'fir' => 'FLFI', 'rating' => 4],
            ['callsign' => 'FLKK_TWR', 'name' => 'Lusaka Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLKS_I_TWR', 'name' => 'Kasama Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLMA_I_TWR', 'name' => 'Mansa Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLMF_APP', 'name' => 'Mfuwe Approach', 'fir' => 'FLFI', 'rating' => 4],
            ['callsign' => 'FLMG_I_TWR', 'name' => 'Mongu Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLND_APP', 'name' => 'Ndola Approach', 'fir' => 'FLFI', 'rating' => 4],
            ['callsign' => 'FLND_TWR', 'name' => 'Ndola Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FLSW_I_TWR', 'name' => 'Solwezi Tower', 'fir' => 'FLFI', 'rating' => 3],
            ['callsign' => 'FMCH_TWR', 'name' => 'Moroni Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMCZ_TWR', 'name' => 'Dzaoudzi Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMEE_APP', 'name' => 'Roland Garros Approach', 'fir' => 'FMMM', 'rating' => 4],
            ['callsign' => 'FMEE_GND', 'name' => 'Roland Garros Ground', 'fir' => 'FMMM', 'rating' => 2],
            ['callsign' => 'FMEE_TWR', 'name' => 'Roland Garros Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMMI_0_GND', 'name' => 'Antananarivo Ground', 'fir' => 'FMMM', 'rating' => 2],
            ['callsign' => 'FMMI_APP', 'name' => 'Antananarivo Approach', 'fir' => 'FMMM', 'rating' => 4],
            ['callsign' => 'FMMI_TWR', 'name' => 'Antananarivo Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMMM_CTR', 'name' => 'Antananarivo Control', 'fir' => 'FMMM', 'rating' => 5],
            ['callsign' => 'FMMT_TWR', 'name' => 'Toamasino Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMNM_TWR', 'name' => 'Mahajanga Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FMNN_TWR', 'name' => 'Nosy Be Tower', 'fir' => 'FMMM', 'rating' => 3],
            ['callsign' => 'FNAN_CTR', 'name' => 'Luanda Control', 'fir' => 'FNAN', 'rating' => 5],
            ['callsign' => 'FNBG_I_TWR', 'name' => 'Benguela Information', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNCA_TWR', 'name' => 'Cabina Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNGI_I_TWR', 'name' => 'Ondjiva Information', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNHU_I_TWR', 'name' => 'Huambo Information', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNLU_APP', 'name' => 'Luanda Approach', 'fir' => 'FNAN', 'rating' => 4],
            ['callsign' => 'FNLU_GND', 'name' => 'Luanda Ground', 'fir' => 'FNAN', 'rating' => 2],
            ['callsign' => 'FNLU_TWR', 'name' => 'Luanda Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNMO_I_TWR', 'name' => 'Namibe Information', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNSA_I_TWR', 'name' => 'Saurimo Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNUB_I_TWR', 'name' => 'Mukanka Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FNUE_I_TWR', 'name' => 'Luena Tower', 'fir' => 'FNAN', 'rating' => 3],
            ['callsign' => 'FOOG_APP', 'name' => 'Port Gentil Approach', 'fir' => 'FCCC', 'rating' => 4],
            ['callsign' => 'FOOG_TWR', 'name' => 'Port Gentil Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FOOL_TWR', 'name' => 'Libreville Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FOON_TWR', 'name' => 'Franceville Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FOOO_CTR', 'name' => 'Libreville Control', 'fir' => 'FCCC', 'rating' => 5],
            ['callsign' => 'FPST_APP', 'name' => 'Sao Tome Approach', 'fir' => 'FCCC', 'rating' => 4],
            ['callsign' => 'FPST_TWR', 'name' => 'Sao Tome Tower', 'fir' => 'FCCC', 'rating' => 3],
            ['callsign' => 'FQBE_CTR', 'name' => 'Beira Control', 'fir' => 'FQBE', 'rating' => 5],
            ['callsign' => 'FQBE_S_CTR', 'name' => 'Maputo Control', 'fir' => 'FQBE', 'rating' => 5],
            ['callsign' => 'FQBR_APP', 'name' => 'Beira Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQBR_GND', 'name' => 'Beira Ground', 'fir' => 'FQBE', 'rating' => 2],
            ['callsign' => 'FQBR_TWR', 'name' => 'Beira Tower', 'fir' => 'FQBE', 'rating' => 3],
            ['callsign' => 'FQLC_TWR', 'name' => 'Lichinga Tower', 'fir' => 'FQBE', 'rating' => 3],
            ['callsign' => 'FQMA_APP', 'name' => 'Maputo Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQMA_GND', 'name' => 'Maputo Ground', 'fir' => 'FQBE', 'rating' => 2],
            ['callsign' => 'FQMA_TWR', 'name' => 'Maputo Tower', 'fir' => 'FQBE', 'rating' => 3],
            ['callsign' => 'FQNC_APP', 'name' => 'Nacala Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQNC_TWR', 'name' => 'Nacala Tower', 'fir' => 'FQBE', 'rating' => 3],
            ['callsign' => 'FQNP_TWR', 'name' => 'Nampula Tower', 'fir' => 'FQBE', 'rating' => 3],
            ['callsign' => 'FQPB_APP', 'name' => 'Pemba Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQQL_APP', 'name' => 'Quelimane Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQTT_APP', 'name' => 'Tete Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FQVL_APP', 'name' => 'Vilankulo Approach', 'fir' => 'FQBE', 'rating' => 4],
            ['callsign' => 'FSIA_APP', 'name' => 'Seychelles Approach', 'fir' => 'FSSS', 'rating' => 4],
            ['callsign' => 'FSIA_GND', 'name' => 'Seychelles Ground', 'fir' => 'FSSS', 'rating' => 2],
            ['callsign' => 'FSIA_TWR', 'name' => 'Seychelles Tower', 'fir' => 'FSSS', 'rating' => 3],
            ['callsign' => 'FSPP_TWR', 'name' => 'Praslin Tower', 'fir' => 'FSSS', 'rating' => 3],
            ['callsign' => 'FSSS_CTR', 'name' => 'Seychelles Control', 'fir' => 'FSSS', 'rating' => 5],
            ['callsign' => 'FAJO_3_FSS', 'name' => 'Johannesburg Oceanic', 'fir' => 'FAJO', 'rating' => 5],
            ['callsign' => 'FVCP_TWR', 'name' => 'Prince Tower', 'fir' => 'FVHF', 'rating' => 3],
            ['callsign' => 'FVCZ_APP', 'name' => 'Buffalo Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVFA_APP', 'name' => 'Falls Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVHF_CTR', 'name' => 'Harare East Control', 'fir' => 'FVHF', 'rating' => 5],
            ['callsign' => 'FVHF_W_CTR', 'name' => 'Harare West Control', 'fir' => 'FVHF', 'rating' => 5],
            ['callsign' => 'FVJN_APP', 'name' => 'Nkomo Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVJN_TWR', 'name' => 'Nkomo Tower', 'fir' => 'FVHF', 'rating' => 3],
            ['callsign' => 'FVKB_APP', 'name' => 'Kariba Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVMV_APP', 'name' => 'Masvingo Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVRG_APP', 'name' => 'Harare Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVRG_GND', 'name' => 'Mugabe Ground', 'fir' => 'FVHF', 'rating' => 2],
            ['callsign' => 'FVRG_TWR', 'name' => 'Mugabe Tower', 'fir' => 'FVHF', 'rating' => 3],
            ['callsign' => 'FVTL_APP', 'name' => 'Thornhill Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FVWN_APP', 'name' => 'Park Approach', 'fir' => 'FVHF', 'rating' => 4],
            ['callsign' => 'FWCL_APP', 'name' => 'Chileka Approach', 'fir' => 'FWLL', 'rating' => 4],
            ['callsign' => 'FWCL_TWR', 'name' => 'Chileka Tower', 'fir' => 'FWLL', 'rating' => 3],
            ['callsign' => 'FWKA_I_TWR', 'name' => 'Karonga Tower', 'fir' => 'FWLL', 'rating' => 3],
            ['callsign' => 'FWKI_APP', 'name' => 'Lilongwe Approach', 'fir' => 'FWLL', 'rating' => 4],
            ['callsign' => 'FWKI_TWR', 'name' => 'Lumbadzi Tower', 'fir' => 'FWLL', 'rating' => 3],
            ['callsign' => 'FWLL_CTR', 'name' => 'Lilongwe Control', 'fir' => 'FWLL', 'rating' => 5],
            ['callsign' => 'FXMM_APP', 'name' => 'Maseru Approach', 'fir' => 'FASA', 'rating' => 4],
            ['callsign' => 'FXMM_GND', 'name' => 'Maseru Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FXMM_TWR', 'name' => 'Maseru Tower', 'fir' => 'FASA', 'rating' => 3],
            ['callsign' => 'FYGF_TWR', 'name' => 'Grootfontein Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYKM_TWR', 'name' => 'Katima Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYKT_TWR', 'name' => 'Keetmanshoop Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYLZ_TWR', 'name' => 'Luderitz Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYOA_APP', 'name' => 'Ondangwa Approach/Tower', 'fir' => 'FYWF', 'rating' => 4],
            ['callsign' => 'FYSM_TWR', 'name' => 'Swakopmund Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYWB_APP', 'name' => 'Walvis Bay Approach/Tower', 'fir' => 'FYWF', 'rating' => 4],
            ['callsign' => 'FYWB_GND', 'name' => 'Walvis Bay Ground', 'fir' => 'FYWF', 'rating' => 2],
            ['callsign' => 'FYWE_A_GND', 'name' => 'Eros Apron', 'fir' => 'FYWF', 'rating' => 2],
            ['callsign' => 'FYWE_TWR', 'name' => 'Eros Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FYWH_A_GND', 'name' => 'Windhoek Apron', 'fir' => 'FYWF', 'rating' => 2],
            ['callsign' => 'FYWH_APP', 'name' => 'Windhoek Approach', 'fir' => 'FYWF', 'rating' => 4],
            ['callsign' => 'FYWH_CTR', 'name' => 'Windhoek Radar', 'fir' => 'FYWF', 'rating' => 5],
            ['callsign' => 'FYWH_TWR', 'name' => 'Windhoek Tower', 'fir' => 'FYWF', 'rating' => 3],
            ['callsign' => 'FZAA_APP', 'name' => 'Kinshasa Approach', 'fir' => 'FZZA', 'rating' => 4],
            ['callsign' => 'FZAA_TWR', 'name' => 'Kinshasa Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZAM_TWR', 'name' => 'Matadi Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZEA_TWR', 'name' => 'Mbandaka Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZFD_TWR', 'name' => 'Gbadolite Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZFK_TWR', 'name' => 'Gemena Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZIC_TWR', 'name' => 'Kisangani Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZJH_TWR', 'name' => 'Isiro Matari Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZKA_TWR', 'name' => 'Bunia Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZKJ_TWR', 'name' => 'Buta Zega Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZMA_TWR', 'name' => 'Bukavu Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZNA_TWR', 'name' => 'Goma Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZOA_TWR', 'name' => 'Kindu Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZQA_APP', 'name' => 'Lubumbashi Approach', 'fir' => 'FZZA', 'rating' => 4],
            ['callsign' => 'FZQA_TWR', 'name' => 'Lubumbashi Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZQM_TWR', 'name' => 'Kolwezi Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZRF_TWR', 'name' => 'Kalemie Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZUA_TWR', 'name' => 'Kananga Tower', 'fir' => 'FZZA', 'rating' => 3],
            ['callsign' => 'FZWA_APP', 'name' => 'Mbuji-Mayi Approach', 'fir' => 'FZZA', 'rating' => 4],
            ['callsign' => 'FZZA_CTR', 'name' => 'Kinshasa Control', 'fir' => 'FZZA', 'rating' => 5],
            ['callsign' => 'FZZA_E_CTR', 'name' => 'Kisangani Control', 'fir' => 'FZZA', 'rating' => 5],
            ['callsign' => 'FZZA_S_CTR', 'name' => 'Lubumbashi Control', 'fir' => 'FZZA', 'rating' => 5],
            ['callsign' => 'GAAA_CTR', 'name' => 'Bamako Control', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GABS_TWR', 'name' => 'Bamako Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GAKD_TWR', 'name' => 'Kayes Dag Dag Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GAMB_TWR', 'name' => 'Mopti Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GBYD_APP', 'name' => 'Banjul Approach', 'fir' => 'GOOO', 'rating' => 4],
            ['callsign' => 'GBYD_TWR', 'name' => 'Banjul Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GFLL_APP', 'name' => 'Freetown Approach', 'fir' => 'GLRB', 'rating' => 4],
            ['callsign' => 'GFLL_TWR', 'name' => 'Freetown Tower', 'fir' => 'GLRB', 'rating' => 3],
            ['callsign' => 'GGOV_APP', 'name' => 'Bissau Approach', 'fir' => 'GOOO', 'rating' => 4],
            ['callsign' => 'GGOV_TWR', 'name' => 'Bissau Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GLRB_APP', 'name' => 'Roberts Approach', 'fir' => 'GLRB', 'rating' => 4],
            ['callsign' => 'GLRB_CTR', 'name' => 'Roberts Control', 'fir' => 'GLRB', 'rating' => 5],
            ['callsign' => 'GLRB_GND', 'name' => 'Roberts Ground', 'fir' => 'GLRB', 'rating' => 2],
            ['callsign' => 'GLRB_TWR', 'name' => 'Roberts Tower', 'fir' => 'GLRB', 'rating' => 3],
            ['callsign' => 'GOBD_APP', 'name' => 'Diass Approach', 'fir' => 'GOOO', 'rating' => 4],
            ['callsign' => 'GOBD_DEL', 'name' => 'Dakar Delivery', 'fir' => 'GOOO', 'rating' => 2],
            ['callsign' => 'GOBD_GND', 'name' => 'Diass Ground', 'fir' => 'GOOO', 'rating' => 2],
            ['callsign' => 'GOBD_TWR', 'name' => 'Diass Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GOGG_TWR', 'name' => 'Ziguinchor Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GOGS_TWR', 'name' => 'Cap-Skirring Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'FAJO_FSS', 'name' => 'Johannesburg Oceanic', 'fir' => 'FAJO', 'rating' => 5],
            ['callsign' => 'GOOO_CTR', 'name' => 'Dakar Control', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GOOY_TWR', 'name' => 'Yoff Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GOSS_TWR', 'name' => 'Saint Louis Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GQNO_TWR', 'name' => 'Nouakchott Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GQPP_TWR', 'name' => 'Nouadhibou Tower', 'fir' => 'GOOO', 'rating' => 3],
            ['callsign' => 'GQQQ_CTR', 'name' => 'Nouakchott Control', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GUCY_APP', 'name' => 'Conakry Approach', 'fir' => 'GLRB', 'rating' => 4],
            ['callsign' => 'GUCY_TWR', 'name' => 'Conakry Tower', 'fir' => 'GLRB', 'rating' => 3],
            ['callsign' => 'GUOK_TWR', 'name' => 'Boke Tower', 'fir' => 'GLRB', 'rating' => 3],
            ['callsign' => 'FSSS_FSS', 'name' => 'Seychelles Control', 'fir' => 'FSSS', 'rating' => 5],
            ['callsign' => 'GVNP_TWR', 'name' => 'Praia Tower', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVSV_TWR', 'name' => 'San Vicente Tower', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVMA_I_TWR', 'name' => 'Maio Information', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVSF_I_TWR', 'name' => 'Sanfilipe Information', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVSN_I_TWR', 'name' => 'Sanicolau Informatio', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVBA_TWR', 'name' => 'Boavista Tower', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVAC_TWR', 'name' => 'Amilcabral Tower', 'fir' => 'GVSC', 'rating' => 3],
            ['callsign' => 'GVSC_DEL', 'name' => 'Sal Delivery', 'fir' => 'GVSC', 'rating' => 2],
            ['callsign' => 'GVAC_0_GND', 'name' => 'Amilcabral Ground', 'fir' => 'GVSC', 'rating' => 2],
            ['callsign' => 'GVSC_APP', 'name' => 'Sal Approach', 'fir' => 'GVSC', 'rating' => 4],
            ['callsign' => 'HBBA_APP', 'name' => 'Bujumbura Approach', 'fir' => 'HBBA', 'rating' => 4],
            ['callsign' => 'HBBA_TWR', 'name' => 'Bujumbura Tower', 'fir' => 'HBBA', 'rating' => 3],
            ['callsign' => 'HKEL_APP', 'name' => 'Eldoret Approach', 'fir' => 'HKNA', 'rating' => 4],
            ['callsign' => 'HKEL_TWR', 'name' => 'Eldoret Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKEM_TWR', 'name' => 'Embu Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKJK_APP', 'name' => 'Nairobi Radar', 'fir' => 'HKNA', 'rating' => 4],
            ['callsign' => 'HKJK_GND', 'name' => 'Nairobi Apron', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKJK_TWR', 'name' => 'Nairobi Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKKI_GND', 'name' => 'Kisumu Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKKI_TWR', 'name' => 'Kisumu Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKLK_GND', 'name' => 'Loki Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKLK_TWR', 'name' => 'Loki Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKML_GND', 'name' => 'Malindi Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKML_TWR', 'name' => 'Malindi Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKMO_APP', 'name' => 'Mombasa Radar', 'fir' => 'HKNA', 'rating' => 4],
            ['callsign' => 'HKMO_GND', 'name' => 'Mombasa Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKMO_TWR', 'name' => 'Mombasa Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKNA_CTR', 'name' => 'Nairobi Control', 'fir' => 'HKNA', 'rating' => 5],
            ['callsign' => 'HKNL_APP', 'name' => 'Nanyuki Approach', 'fir' => 'HKNA', 'rating' => 4],
            ['callsign' => 'HKNW_GND', 'name' => 'Wilson Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKNW_TWR', 'name' => 'Wilson Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKRE_TWR', 'name' => 'Eastleigh Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HKWJ_GND', 'name' => 'Wajir Ground', 'fir' => 'HKNA', 'rating' => 2],
            ['callsign' => 'HKWJ_TWR', 'name' => 'Wajir Tower', 'fir' => 'HKNA', 'rating' => 3],
            ['callsign' => 'HRYG_TWR', 'name' => 'Gisenyl Tower', 'fir' => 'HRYR', 'rating' => 3],
            ['callsign' => 'HRYR_APP', 'name' => 'Kigali Approach', 'fir' => 'HRYR', 'rating' => 4],
            ['callsign' => 'HRYR_TWR', 'name' => 'Kigali Tower', 'fir' => 'HRYR', 'rating' => 3],
            ['callsign' => 'HRZA_TWR', 'name' => 'Kamembe Tower', 'fir' => 'HRYR', 'rating' => 3],
            ['callsign' => 'HTDA_APP', 'name' => 'Dar-Es-Salaam Approach', 'fir' => 'HTDC', 'rating' => 4],
            ['callsign' => 'HTDA_GND', 'name' => 'Dar-Es-Salaam Ground', 'fir' => 'HTDC', 'rating' => 2],
            ['callsign' => 'HTDA_TWR', 'name' => 'Dar-Es-Salaam Tower', 'fir' => 'HTDC', 'rating' => 3],
            ['callsign' => 'HTDC_CTR', 'name' => 'Dar-Es-Salaam Control', 'fir' => 'HTDC', 'rating' => 5],
            ['callsign' => 'HTDO_APP', 'name' => 'Dodoma Approach', 'fir' => 'HTDC', 'rating' => 4],
            ['callsign' => 'HTKJ_APP', 'name' => 'Kilimanjaro Approach', 'fir' => 'HTDC', 'rating' => 4],
            ['callsign' => 'HTKJ_TWR', 'name' => 'Kilimamjaro Tower', 'fir' => 'HTDC', 'rating' => 3],
            ['callsign' => 'HTMW_APP', 'name' => 'Mwanza Approach', 'fir' => 'HTDC', 'rating' => 4],
            ['callsign' => 'HTMW_TWR', 'name' => 'Mwanza Tower', 'fir' => 'HTDC', 'rating' => 3],
            ['callsign' => 'HTZA_APP', 'name' => 'Zanzibar Approach', 'fir' => 'HTDC', 'rating' => 4],
            ['callsign' => 'HUEC_CTR', 'name' => 'Entebbe Control', 'fir' => 'HUEC', 'rating' => 5],
            ['callsign' => 'HUEN_APP', 'name' => 'Entebbe Approach', 'fir' => 'HUEC', 'rating' => 4],
            ['callsign' => 'HUEN_GND', 'name' => 'Entebbe Ground', 'fir' => 'HUEC', 'rating' => 2],
            ['callsign' => 'HUEN_TWR', 'name' => 'Entebbe Tower', 'fir' => 'HUEC', 'rating' => 3],
            ['callsign' => 'HUSO_APP', 'name' => 'Soroti Approach', 'fir' => 'HUEC', 'rating' => 4],
            ['callsign' => 'HUSO_TWR', 'name' => 'Soroti Tower', 'fir' => 'HUEC', 'rating' => 3],
            ['callsign' => 'GVSC_U_APP', 'name' => 'Sal Approach', 'fir' => 'GVSC', 'rating' => 4],
            ['callsign' => 'GOOY_GND', 'name' => 'Yoff Ground', 'fir' => 'GOOO', 'rating' => 2],
            ['callsign' => 'DNMM_DEL', 'name' => 'Lagos Delivery', 'fir' => 'DNKK', 'rating' => 2],
            ['callsign' => 'DNMM_P_DEL', 'name' => 'Lagos Planner', 'fir' => 'DNKK', 'rating' => 2],
            ['callsign' => 'DNMM_E_GND', 'name' => 'Lagos Ground', 'fir' => 'DNKK', 'rating' => 2],
            ['callsign' => 'GOOC_A_FSS', 'name' => 'Dakar Radio', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GOOC_B_FSS', 'name' => 'Dakar Radio', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GOOC_FSS', 'name' => 'Dakar Radio', 'fir' => 'GOOO', 'rating' => 5],
            ['callsign' => 'GVSC_CTR', 'name' => 'Sal Control', 'fir' => 'GVSC', 'rating' => 5],
            ['callsign' => 'FACT_P_DEL', 'name' => 'Cape Town Planner', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'FACT_E_GND', 'name' => 'Cape Town Ground', 'fir' => 'FASA', 'rating' => 2],
            ['callsign' => 'GOBD_U_APP', 'name' => 'Dakar Approach', 'fir' => 'GOOO', 'rating' => 4],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('positions');
    }
}
